// Code generated by "stringer -type DataType"; DO NOT EDIT.

package sticktable

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataTypeServerId-0]
	_ = x[DataTypeGPT0-1]
	_ = x[DataTypeGPC0-2]
	_ = x[DataTypeGPC0Rate-3]
	_ = x[DataTypeConnectionsCounter-4]
	_ = x[DataTypeConnectionRate-5]
	_ = x[DataTypeNumberOfCurrentConnections-6]
	_ = x[DataTypeSessionsCounter-7]
	_ = x[DataTypeSessionRate-8]
	_ = x[DataTypeHttpRequestsCounter-9]
	_ = x[DataTypeHttpRequestsRate-10]
	_ = x[DataTypeErrorsCounter-11]
	_ = x[DataTypeErrorsRate-12]
	_ = x[DataTypeBytesInCounter-13]
	_ = x[DataTypeBytesInRate-14]
	_ = x[DataTypeBytesOutCounter-15]
	_ = x[DataTypeBytesOutRate-16]
	_ = x[DataTypeGPC1-17]
	_ = x[DataTypeGPC1Rate-18]
	_ = x[DataTypeServerKey-19]
	_ = x[DataTypeHttpFailCounter-20]
	_ = x[DataTypeHttpFailRate-21]
	_ = x[DataTypeGPTArray-22]
	_ = x[DataTypeGPCArray-23]
	_ = x[DataTypeGPCRateArray-24]
}

const _DataType_name = "DataTypeServerIdDataTypeGPT0DataTypeGPC0DataTypeGPC0RateDataTypeConnectionsCounterDataTypeConnectionRateDataTypeNumberOfCurrentConnectionsDataTypeSessionsCounterDataTypeSessionRateDataTypeHttpRequestsCounterDataTypeHttpRequestsRateDataTypeErrorsCounterDataTypeErrorsRateDataTypeBytesInCounterDataTypeBytesInRateDataTypeBytesOutCounterDataTypeBytesOutRateDataTypeGPC1DataTypeGPC1RateDataTypeServerKeyDataTypeHttpFailCounterDataTypeHttpFailRateDataTypeGPTArrayDataTypeGPCArrayDataTypeGPCRateArray"

var _DataType_index = [...]uint16{0, 16, 28, 40, 56, 82, 104, 138, 161, 180, 207, 231, 252, 270, 292, 311, 334, 354, 366, 382, 399, 422, 442, 458, 474, 494}

func (i DataType) String() string {
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
