// Code generated by "stringer -type MessageType"; DO NOT EDIT.

package sticktable

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageEntryUpdate-128]
	_ = x[MessageIncrementalEntryUpdate-129]
	_ = x[MessageStickTableDefinition-130]
	_ = x[MessageStickTableSwitch-131]
	_ = x[MessageUpdateAcknowledge-132]
	_ = x[MessageUpdateTimed-133]
	_ = x[MessageIncrementalEntryUpdateTimed-134]
}

const _MessageType_name = "MessageEntryUpdateMessageIncrementalEntryUpdateMessageStickTableDefinitionMessageStickTableSwitchMessageUpdateAcknowledgeMessageUpdateTimedMessageIncrementalEntryUpdateTimed"

var _MessageType_index = [...]uint8{0, 18, 47, 74, 97, 121, 139, 173}

func (i MessageType) String() string {
	i -= 128
	if i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i+128), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
