// Code generated by "stringer -type ErrorMessageType"; DO NOT EDIT.

package peers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorMessageProtocol-0]
	_ = x[ErrorMessageSizeLimit-1]
}

const _ErrorMessageType_name = "ErrorMessageProtocolErrorMessageSizeLimit"

var _ErrorMessageType_index = [...]uint8{0, 20, 41}

func (i ErrorMessageType) String() string {
	if i >= ErrorMessageType(len(_ErrorMessageType_index)-1) {
		return "ErrorMessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorMessageType_name[_ErrorMessageType_index[i]:_ErrorMessageType_index[i+1]]
}
