// Code generated by "stringer -type HandshakeStatus"; DO NOT EDIT.

package peers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusHandshakeSucceeded-200]
	_ = x[StatusTryAgainLater-300]
	_ = x[StatusProtocolError-501]
	_ = x[StatusBadVersion-502]
	_ = x[StatusLocalPeerIdentifierMismatch-503]
	_ = x[StatusRemotePeerIdentifierMismatch-504]
}

const (
	_HandshakeStatus_name_0 = "StatusHandshakeSucceeded"
	_HandshakeStatus_name_1 = "StatusTryAgainLater"
	_HandshakeStatus_name_2 = "StatusProtocolErrorStatusBadVersionStatusLocalPeerIdentifierMismatchStatusRemotePeerIdentifierMismatch"
)

var (
	_HandshakeStatus_index_2 = [...]uint8{0, 19, 35, 68, 102}
)

func (i HandshakeStatus) String() string {
	switch {
	case i == 200:
		return _HandshakeStatus_name_0
	case i == 300:
		return _HandshakeStatus_name_1
	case 501 <= i && i <= 504:
		i -= 501
		return _HandshakeStatus_name_2[_HandshakeStatus_index_2[i]:_HandshakeStatus_index_2[i+1]]
	default:
		return "HandshakeStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
