// Code generated by "stringer -type MessageClass"; DO NOT EDIT.

package peers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageClassControl-0]
	_ = x[MessageClassError-1]
	_ = x[MessageClassStickTableUpdates-10]
	_ = x[MessageClassReserved-255]
}

const (
	_MessageClass_name_0 = "MessageClassControlMessageClassError"
	_MessageClass_name_1 = "MessageClassStickTableUpdates"
	_MessageClass_name_2 = "MessageClassReserved"
)

var (
	_MessageClass_index_0 = [...]uint8{0, 19, 36}
)

func (i MessageClass) String() string {
	switch {
	case i <= 1:
		return _MessageClass_name_0[_MessageClass_index_0[i]:_MessageClass_index_0[i+1]]
	case i == 10:
		return _MessageClass_name_1
	case i == 255:
		return _MessageClass_name_2
	default:
		return "MessageClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
