// Code generated by "stringer -type StickTableDataType"; DO NOT EDIT.

package peers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StickTableDataTypeServerId-0]
	_ = x[StickTableDataTypeGPT0-1]
	_ = x[StickTableDataTypeGPC0-2]
	_ = x[StickTableDataTypeGPC0Rate-3]
	_ = x[StickTableDataTypeConnectionsCounter-4]
	_ = x[StickTableDataTypeConnectionRate-5]
	_ = x[StickTableDataTypeNumberOfCurrentConnections-6]
	_ = x[StickTableDataTypeSessionsCounter-7]
	_ = x[StickTableDataTypeSessionRate-8]
	_ = x[StickTableDataTypeHttpRequestsCounter-9]
	_ = x[StickTableDataTypeHttpRequestsRate-10]
	_ = x[StickTableDataTypeErrorsCounter-11]
	_ = x[StickTableDataTypeErrorsRate-12]
	_ = x[StickTableDataTypeBytesInCounter-13]
	_ = x[StickTableDataTypeBytesInRate-14]
	_ = x[StickTableDataTypeBytesOutCounter-15]
	_ = x[StickTableDataTypeBytesOutRate-16]
	_ = x[StickTableDataTypeGPC1-17]
	_ = x[StickTableDataTypeGPC1Rate-18]
	_ = x[StickTableDataTypeServerKey-19]
	_ = x[StickTableDataTypeHttpFailCounter-20]
	_ = x[StickTableDataTypeHttpFailRate-21]
	_ = x[StickTableDataTypeGPTArray-22]
	_ = x[StickTableDataTypeGPCArray-23]
	_ = x[StickTableDataTypeGPCRateArray-24]
}

const _StickTableDataType_name = "StickTableDataTypeServerIdStickTableDataTypeGPT0StickTableDataTypeGPC0StickTableDataTypeGPC0RateStickTableDataTypeConnectionsCounterStickTableDataTypeConnectionRateStickTableDataTypeNumberOfCurrentConnectionsStickTableDataTypeSessionsCounterStickTableDataTypeSessionRateStickTableDataTypeHttpRequestsCounterStickTableDataTypeHttpRequestsRateStickTableDataTypeErrorsCounterStickTableDataTypeErrorsRateStickTableDataTypeBytesInCounterStickTableDataTypeBytesInRateStickTableDataTypeBytesOutCounterStickTableDataTypeBytesOutRateStickTableDataTypeGPC1StickTableDataTypeGPC1RateStickTableDataTypeServerKeyStickTableDataTypeHttpFailCounterStickTableDataTypeHttpFailRateStickTableDataTypeGPTArrayStickTableDataTypeGPCArrayStickTableDataTypeGPCRateArray"

var _StickTableDataType_index = [...]uint16{0, 26, 48, 70, 96, 132, 164, 208, 241, 270, 307, 341, 372, 400, 432, 461, 494, 524, 546, 572, 599, 632, 662, 688, 714, 744}

func (i StickTableDataType) String() string {
	if i < 0 || i >= StickTableDataType(len(_StickTableDataType_index)-1) {
		return "StickTableDataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StickTableDataType_name[_StickTableDataType_index[i]:_StickTableDataType_index[i+1]]
}
