// Code generated by "stringer -type StickTableMessageType"; DO NOT EDIT.

package peers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StickTableMessageEntryUpdate-128]
	_ = x[StickTableMessageIncrementalEntryUpdate-129]
	_ = x[StickTableMessageStickTableDefinition-130]
	_ = x[StickTableMessageStickTableSwitch-131]
	_ = x[StickTableMessageUpdateAcknowledge-132]
	_ = x[StickTableMessageUpdateTimed-133]
	_ = x[StickTableMessageIncrementalEntryUpdateTimed-134]
}

const _StickTableMessageType_name = "StickTableMessageEntryUpdateStickTableMessageIncrementalEntryUpdateStickTableMessageStickTableDefinitionStickTableMessageStickTableSwitchStickTableMessageUpdateAcknowledgeStickTableMessageUpdateTimedStickTableMessageIncrementalEntryUpdateTimed"

var _StickTableMessageType_index = [...]uint8{0, 28, 67, 104, 137, 171, 199, 243}

func (i StickTableMessageType) String() string {
	i -= 128
	if i >= StickTableMessageType(len(_StickTableMessageType_index)-1) {
		return "StickTableMessageType(" + strconv.FormatInt(int64(i+128), 10) + ")"
	}
	return _StickTableMessageType_name[_StickTableMessageType_index[i]:_StickTableMessageType_index[i+1]]
}
