// Code generated by "stringer -type StickTableKeyType"; DO NOT EDIT.

package peers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StickTableKeyTypeAny-0]
	_ = x[StickTableKeyTypeBoolean-1]
	_ = x[StickTableKeyTypeSignedInteger-2]
	_ = x[StickTableKeyTypeAddress-3]
	_ = x[StickTableKeyTypeIPv4Address-4]
	_ = x[StickTableKeyTypeIPv6Address-5]
	_ = x[StickTableKeyTypeString-6]
	_ = x[StickTableKeyTypeBinary-7]
	_ = x[StickTableKeyTypeMethod-8]
}

const _StickTableKeyType_name = "StickTableKeyTypeAnyStickTableKeyTypeBooleanStickTableKeyTypeSignedIntegerStickTableKeyTypeAddressStickTableKeyTypeIPv4AddressStickTableKeyTypeIPv6AddressStickTableKeyTypeStringStickTableKeyTypeBinaryStickTableKeyTypeMethod"

var _StickTableKeyType_index = [...]uint8{0, 20, 44, 74, 98, 126, 154, 177, 200, 223}

func (i StickTableKeyType) String() string {
	if i < 0 || i >= StickTableKeyType(len(_StickTableKeyType_index)-1) {
		return "StickTableKeyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StickTableKeyType_name[_StickTableKeyType_index[i]:_StickTableKeyType_index[i+1]]
}
