name: Go

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./...

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run go generate
        run: |
          go install golang.org/x/tools/cmd/stringer
          
          go generate ./...
          git diff --exit-code || (echo "Generated files have changed. Please run 'go generate' and commit the changes." && exit 1)

      - name: Validate
        run: |
          go mod tidy
          git diff --exit-code || (echo "go.mod or go.sum have changed. Please run 'go mod tidy' and commit the changes." && exit 1)

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test
        run: go test -v ./...

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: setup environment
        run: |
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
          sudo apt-get update
          sudo apt-get install -y haproxy
          haproxy -vv

      - name: Test E2E
        run: go test -v ./... --tags=e2e