name: Go

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./...

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run go generate
        run: |
          cd internal/tools
          go install golang.org/x/tools/cmd/stringer
          cd ../..
          
          go generate ./...
          git diff --exit-code || (echo "Generated files have changed. Please run 'go generate' and commit the changes." && exit 1)

      - name: Validate
        run: |
          go mod tidy
          git diff --exit-code || (echo "go.mod or go.sum have changed. Please run 'go mod tidy' and commit the changes." && exit 1)

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"

      - uses: actions/checkout@v3

      - name: Test E2E
        run: earthly +test